document.writeln("<style type=\"text/css\" />");
document.writeln('body, button, input, select, textarea {');
document.writeln('	font: 12px/1.5 "微软雅黑",Verdana, Geneva, sans-serif, tahoma, Srial, helvetica, sans-serif;');
document.writeln('}');

document.writeln('.clearfix:before,.clearfix:after {content:"";display:table;}');
document.writeln('.clearfix:after {clear:both;overflow:hidden;}');
document.writeln('.clearfix {zoom:1;}');
document.writeln('.pubW1{ width:1190px; margin:0 auto}');
document.writeln('.center{ margin:0 auto;}');

document.writeln('.footer_logo,.zxmr,.wzx,.pfmr,.kqmr,.mfzz,.footer_wx dl dd,.submit_btn,.footer_secicon1,.footer_secicon2,.footer_secicon3,.footer_secicon4,.footer_secicon5,.footer_secicon6,.footer_secicon7,.footer_secicon8{ background:url(http://www.shhuamei.cn/img/footer_icon.png) no-repeat;}');
document.writeln('#footer {width:100%;padding:30px 0 0 0; background-color:#414141;/*margin-top:20px; */overflow:hidden;}');
document.writeln('.footer_logo {width:121px;height:125px;  background-position:-20px -29px;float:left;margin-top:75px;margin-left:25px;display:inline;margin-right:40px;}');
document.writeln('.footer_border,.footer_border1 {border-left:1px dashed #363636;float:left;width:1px;height:206px;margin:20px 35px 0 20px;display:inline;}');
document.writeln('.footer_list {width:625px;float:left;overflow:hidden;margin-top:15px;}');
document.writeln('.footer_list > li {float:left;color:#a7a7a7;margin-right:40px;display:inline;}');
document.writeln('.footer_list li span {display:block;float:left;height:31px;line-height:31px;border-bottom:1px solid #303030;font-size:14px;margin-bottom:10px;}');
document.writeln('.footer_list a { transition: all 0.3s linear 0s;padding:3px;display:block;}');
document.writeln('.footer_list a:hover { color:#FFF; background-color:#303030;}');
document.writeln('.footer_list li span a {color:#d6d6d6;text-decoration:none;display:block;height:22px;line-height:22px;float:left;}');
document.writeln('.zxmr {width:65px;height:31px; background-position:-2px -180px; padding-left:21px;}');
document.writeln('.wzx {width:65px;height:31px; padding-left:21px;background-position:-159px -182px;}');
document.writeln('.pfmr {width:65px;height:31px;padding-left:21px; background-position:-332px -182px;}'); 
document.writeln('.kqmr {height:31px;padding-left:21px; background-position:-509px -184px;} ');
document.writeln('.mfzz {height:31px;padding-left:21px; background-position:-237px -130px;} ');
document.writeln('.footer_list li ul {float:left;padding-left:3px;overflow:hidden;}');
document.writeln('.zxmr_ul li {width:87px;height:22px;line-height:22px;float:left;font-size:12px;overflow:hidden;}');
document.writeln('.zxmr_ul li a { display:block;height:16px;line-height:16px;text-decoration:none;float:left;margin-right:8px;display:inline;color:#a7a7a7;}');
document.writeln('.kqmr_ul  {width:102px;}');
document.writeln('.kqmr_ul li {width:102px;height:22px;line-height:22px;float:left;font-size:12px;overflow:hidden;}');
document.writeln('.kqmr_ul li a {display:block;text-decoration:none;float:left;margin-right:8px;display:inline;color:#a7a7a7;height:16px;line-height:16px;}');
document.writeln('.mfzz_ul li {width:137px;height:22px;line-height:22px;float:left;font-size:12px;overflow:hidden;}');
document.writeln('.mfzz_ul li a {display:block;text-decoration:none;float:left;margin-right:8px;display:inline;color:#a7a7a7;height:16px;line-height:16px;}');
document.writeln('.footer_wx {width:234px;float:left;height:225px;color:#a7a7a7;}');
document.writeln('.footer_wx dl {width:234px;float:left;height:77px;margin:10px 0 5px;}');
document.writeln('.footer_wx dl dd {float:left;width:77px;height:77px; background-position:-359px -50px;}');
document.writeln('.footer_wx dl dt {float:left;margin-left:10px;display:inline;margin-top:3px;}');
document.writeln('.footer_wx p {width:234px;line-height:22px;float:left;font-size:14px;}');
document.writeln('.footer_search {width:234px;height:32px;float:left; background:url(http://www.shhuamei.cn/img/footer_searchbg.jpg) no-repeat;margin-top:15px;}');
document.writeln('.footer_search .footer_search_text {width:176px;height:32px;float:left;}');
document.writeln('.footer_search .footer_search_text input {width:170px;height:26px;line-height:26px;padding:0;margin:3px;border:none; background-color:#FFF}');
document.writeln('.footer_search .footer_search_btn {width:57px;height:30px;float:left;margin-top:1px;}');
document.writeln('.footer_search .footer_search_btn input { background-position:-362px -141px;width:57px;height:30px;padding:0;border:none;cursor:pointer;}');
document.writeln('.footer_search .footer_search_btn input:hover { background-position:-435px -141px;}');
document.writeln('#footer hr {width:100%;float:left;height:1px;margin-top:25px; background-color:#303030;border:none;}');
document.writeln('.footer_secicon {width:100%;height:100px;float:left;padding-top:20px;}');
document.writeln('.footer_secicon li {width:85px;height:100px;float:left;margin-left:10px;margin-right:50px;display:inline;}');
document.writeln('.footer_secicon li:nth-child(1) {margin-left:35px;}');
document.writeln('.footer_secicon li i {width:48px;height:48px;float:left;margin-left:18px;display:inline;display:block;cursor:pointer;}');
document.writeln('.footer_secicon li span {width:100%;height:40px;line-height:40px;font-size:16px;text-align:center;color:#a7a7a7;float:left;}');
document.writeln('.footer_secicon1 { background-position:-23px -264px;}');
document.writeln('.footer_secicon2 { background-position:-87px -264px;}');
document.writeln('.footer_secicon3 { background-position:-151px -264px;}');
document.writeln('.footer_secicon4 { background-position:-215px -264px;}');
document.writeln('.footer_secicon5 { background-position:-280px -264px;}');
document.writeln('.footer_secicon6 { background-position:-344px -264px;}');
document.writeln('.footer_secicon7 { background-position:-408px -264px;}');
document.writeln('.footer_secicon8 { background-position:-472px -264px;}');
document.writeln('.footer_secicon li:hover .footer_secicon1 { background-position:-23px -324px;}');
document.writeln('.footer_secicon li:hover .footer_secicon2 { background-position:-87px -324px;}');
document.writeln('.footer_secicon li:hover .footer_secicon3 { background-position:-151px -324px;}');
document.writeln('.footer_secicon li:hover .footer_secicon4 { background-position:-215px -324px;}');
document.writeln('.footer_secicon li:hover .footer_secicon5 { background-position:-280px -324px;}');
document.writeln('.footer_secicon li:hover .footer_secicon6 { background-position:-344px -324px;}');
document.writeln('.footer_secicon li:hover .footer_secicon7 { background-position:-408px -324px;}');
document.writeln('.footer_secicon li:hover .footer_secicon8 { background-position:-472px -324px;}');
document.writeln('.footer_copyright {width:100%;height:35px;line-height:35px;font-size:12px;color:#a7a7a7;text-align:center; background-color:#303030;}');
/*document.writeln('.footer_logo {display:none;}');
document.writeln('.footer_border {display:none;}');*/
document.writeln('.footer_list {margin-left:30px;}');
document.writeln("</style>");


document.writeln('<div id="footer">');
document.writeln('  <div class="pubW1 center clearfix">');
document.writeln('    <h2 class="footer_logo"></h2>');
document.writeln('    <h3 class="footer_border"></h3>');
document.writeln('    <ul class="footer_list">');
document.writeln('      <li style="width:90px;"> <span class="zxmr"><a href="http://baidu.shhuamei.cn/web_htm/zhenxin/" target="_blank">整形美容</a></span>');
document.writeln('        <ul class="zxmr_ul">');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/east_hans/" target="_blank">眼部整形</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/east_biz/" target="_blank">鼻部整形</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/east_xe/" target="_blank">面部轮廓</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/east_rufa/" target="_blank">乳房整形</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/east_xizi/" target="_blank">吸脂塑身</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/chun/" target="_blank">唇部整形</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/zitizhifang/" target="_blank">自体脂肪移植</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/east_szhi/" target="_blank">私密整形</a></li>');
document.writeln('        </ul>');
document.writeln('      </li>');
document.writeln('      <li style="width:82px;"> <span class="zxmr wzx"><a href="http://baidu.shhuamei.cn/zsmr/" target="_blank">注射美容</a></span>');
document.writeln('        <ul class="zxmr_ul">');
document.writeln('         <li><a href="http://baidu.shhuamei.cn/zscz/" target="_blank">注射除皱</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/zxtc/" target="_blank">面部填充</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/slz/" target="_blank">注射瘦脸</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/stz/" target="_blank">注射瘦腿</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/sbmr/" target="_blank">手背美容</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/zscl/" target="_blank">注射材料</a></li>');
document.writeln('        </ul>');
document.writeln('      </li>');
document.writeln('      <li style="width:82px;"> <span class="zxmr pfmr"><a href="http://baidu.shhuamei.cn/meirongzhuanqu/" target="_blank">皮肤美容</a></span>');
document.writeln('        <ul class="zxmr_ul">');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/east_caig/" target="_blank">美白嫩肤</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/qubanqudou/" target="_blank">祛斑</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/qudou/" target="_blank">祛痘祛印</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/shepinchuzhou/" target="_blank">射频除皱</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/xgxzz/" target="_blank">血管性症状</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/east_tuom/" target="_blank">冰点脱毛</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/yechou/" target="_blank">除腋臭</a></li>');
document.writeln('        </ul>');
document.writeln('      </li>');
document.writeln('      <li style="width:105px;"> <span class="zxmr kqmr"><a href="http://baidu.shhuamei.cn/web_htm/east_kou/" target="_blank">口腔美容</a></span>');
document.writeln('        <ul class="kqmr_ul">');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/mrguan/" target="_blank">美容冠</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/zhongzhiya/" target="_blank">种植牙</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/buya/" target="_blank">补牙</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/yzjb/" target="_blank">牙周疾病</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/ytm/" target="_blank">牙贴面</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/kaoya/" target="_blank">烤瓷牙</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/zenya/" target="_blank">牙齿矫正</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/web_htm/mya/" target="_blank">牙齿美白</a></li>');
document.writeln('        </ul>');
document.writeln('      </li>');
document.writeln('      <li style="width:105px;margin-right:0;"> <span class="zxmr mfzz"><a href="http://baidu.shhuamei.cn/zhifa/" target="_blank">毛发种植</a></span>');
document.writeln('        <ul class="mfzz_ul">');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/toufazhongzhi/" target="_blank">头发种植</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/meimaozhongzhi/" target="_blank">眉毛种植</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/jiemaozhongzhi/" target="_blank">睫毛种植</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/zhifa/zie2/" target="_blank">胡须种植</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/binjiaozhongzhi/" target="_blank">鬓角种植</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/bahenzhongzhi/" target="_blank">疤痕种植</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/fajixiantiaozheng/" target="_blank">发际线调整</a></li>');
document.writeln('          <li><a href="http://baidu.shhuamei.cn/meirenjianzhongzhi/" target="_blank">美人尖种植</a></li>');
document.writeln('        </ul>');
document.writeln('      </li>');
document.writeln('    </ul>');
document.writeln('    <h3 class="footer_border1"></h3>');
document.writeln('    <div class="footer_wx">');
document.writeln('     <dl>');
document.writeln('        <dd><a href="javascript:void(0);" class="btn_wx"></a></dd>');
document.writeln('        <dt style="font-size:16px;">华美官方微信</dt>');
document.writeln('        <dt>上海华美医疗美容医院</dt>');
document.writeln('        <dt>shhuamei021</dt>');
document.writeln('      </dl>');
document.writeln('      <p style="margin-top:10px;">医院地址：上海市源深路155号</p>');
document.writeln('      <p>免费热线：400 880 6580</p>');
document.writeln('      <p>医院电话：021-5885 6655</p>');
document.writeln('      <div class="footer_search">');
document.writeln('        <form action="http://baidu.shhuamei.cn/search.php" name="search_footer" method="get" target="_blank">');
document.writeln('          <div class="footer_search_text">');
document.writeln('            <input type="text" value="双眼皮"  style="font-size:12px;color:#b4b4b4" onfocus=\'if(this.value=="双眼皮") {this.value=""}\' onblur="if(this.value==\'\'){this.value=\'双眼皮\'}" class="search_text" name="keyword"/>');
document.writeln('          </div>');
document.writeln('          <div class="footer_search_btn">');
document.writeln('            <input type="submit" value="" name="submit_btn" class="submit_btn"/>');
document.writeln('          </div>');
document.writeln('        </form>');
document.writeln('      </div>');
document.writeln('    </div>');
document.writeln('    <div class="clear"></div>');
document.writeln('    <hr/>');
document.writeln('    <ul class="footer_secicon">');
document.writeln('      <li><i class="footer_secicon1"></i><span>顾客体系</span></li>');
document.writeln('      <li><i class="footer_secicon2"></i><span>术前严检</span></li>');
document.writeln('      <li><i class="footer_secicon3"></i><span>专家资质</span></li>');
document.writeln('      <li><i class="footer_secicon4"></i><span>材料安全</span></li>');
document.writeln('      <li><i class="footer_secicon5"></i><span>设备安全</span></li>');
document.writeln('      <li><i class="footer_secicon6"></i><span>手术安全</span></li>');
document.writeln('      <li><i class="footer_secicon7"></i><span>术后管理</span></li>');
document.writeln('      <li><i class="footer_secicon8"></i><span>承诺保障</span></li>');
document.writeln('    </ul>');
document.writeln('  </div>');
document.writeln('  <div class="footer_copyright">CopyRight 1998-2014 ShangHai HuaMei All Rights Reserved &nbsp;&nbsp;&nbsp;&nbsp;    沪ICP备13030768号-1 &nbsp;&nbsp;&nbsp;&nbsp;    沪卫（中医）网审【2012】第10026号</div>');
document.writeln('</div>');



/*
document.writeln('<footer class=\"top20 dhone\">');
document.writeln('  <div id="footer">');
document.writeln('	<div class="foologo none980 block1190"><img src="i21.jpg"/*tpa=http://baidu.shhuamei.cn/img/i21.jpg*/ width="164" height="79"></div>');
document.writeln('	<div id="footer_nav">');
document.writeln('	  <ul>');
document.writeln('		<li>');
document.writeln('		  <h3 id="footer_nav_ioc1"><a href="http://baidu.shhuamei.cn/web_htm/zhenxin/" target="_blank">整形美容</a></h3>');
document.writeln('		</li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/east_hans/" target="_blank">眼部整形</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/east_biz/" target="_blank">鼻部整形</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/east_xe/" target="_blank">面部轮廓</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/east_rufa/" target="_blank">乳房整形</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/east_xizi/" target="_blank">吸脂塑身</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/chun/" target="_blank">唇部整形</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/zitizhifang/" target="_blank">自体脂肪移植</a></li>'); 
document.writeln('		<li><a href="	http://baidu.shhuamei.cn/web_htm/east_szhi/" target="_blank">私密整形</a></li>');
document.writeln('	  </ul>');
document.writeln('	  <ul>');
document.writeln('		<li>');
document.writeln('		  <h3 id="footer_nav_ioc2"><a href="http://baidu.shhuamei.cn/zsmr/" target="_blank">注射美容</a></h3>');
document.writeln('		</li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/zscz/" target="_blank">注射除皱</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/zxtc/" target="_blank">面部填充</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/slz/" target="_blank">注射瘦脸</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/stz/" target="_blank">注射瘦腿</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/sbmr/" target="_blank">手背美容</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/zscl/" target="_blank">注射材料</a></li>');
document.writeln('	  </ul>');
document.writeln('	  <ul>');
document.writeln('		<li>');
document.writeln('		  <h3 id="footer_nav_ioc3"><a href="http://baidu.shhuamei.cn/meirongzhuanqu/" target="_blank">皮肤美容</a></h3>');
document.writeln('		</li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/east_caig/" target="_blank">美白嫩肤</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/qubanqudou/" target="_blank">祛斑</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/qudou/" target="_blank">祛痘祛印</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/shepinchuzhou/" target="_blank">射频除皱</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/xgxzz/" target="_blank">血管性症状</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/east_tuom/" target="_blank">冰点脱毛</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/yechou/" target="_blank">除腋臭</a></li>');
document.writeln('	  </ul>');
document.writeln('	  <ul>');
document.writeln('		<li>');
document.writeln('		  <h3 id="footer_nav_ioc4"><a href="http://baidu.shhuamei.cn/web_htm/east_kou/" target="_blank">口腔美容</a></h3>');
document.writeln('		</li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/mrguan/" target="_blank">美容冠</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/zhongzhiya/" target="_blank">种植牙</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/buya/" target="_blank">补牙</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/yzjb/" target="_blank">牙周疾病</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/ytm/" target="_blank">牙贴面</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/kaoya/" target="_blank">烤瓷牙</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/zenya/" target="_blank">牙齿矫正</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/web_htm/mya/" target="_blank">牙齿美白</a></li>');
document.writeln('	  </ul>');
document.writeln('	  <ul>');
document.writeln('		<li>');
document.writeln('		  <h3 id="footer_nav_ioc5"><a href="http://baidu.shhuamei.cn/zhifa/" target="_blank">毛发种植</a></h3>');
document.writeln('		</li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/toufazhongzhi/" target="_blank">头发种植</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/meimaozhongzhi/" target="_blank">眉毛种植</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/jiemaozhongzhi/" target="_blank">睫毛种植</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/zhifa/zie2/" target="_blank">胡须种植</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/binjiaozhongzhi/" target="_blank">鬓角种植</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/bahenzhongzhi/" target="_blank">疤痕种植</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/fajixiantiaozheng/" target="_blank">发际线调整</a></li>');
document.writeln('		<li><a href="http://baidu.shhuamei.cn/meirenjianzhongzhi/" target="_blank">美人尖种植</a></li>');
document.writeln('	  </ul>');
document.writeln('	</div>');
document.writeln('	<div id="footer_copyright">');
document.writeln('	  <div id="footer_copyright_img"><img src="sm.png"/*tpa=http://baidu.shhuamei.cn/img/sm.png*/ width="77" height="77"></div>');
document.writeln('	  <div id="footer_copyright_txt">');
document.writeln('		<h3>华美官方微信</h3>');
document.writeln('		上海华美医疗美容医院<br>');
document.writeln('		<a href="http://baidu.shhuamei.cn/sitemap.html" target="_blank">网站地图</a> | <a href="http://baidu.shhuamei.cn/sitemap.xml" target="_blank">sitemap</a></div>');
document.writeln('	  <div id="footer_copyright_txttwo">医院地址：上海市源深路155号(近乳山路)<br>');
document.writeln('		沪ICP备13030768号-1 &nbsp;&nbsp;&nbsp;&nbsp;');
document.writeln('		<script type="text/javascript"> ');
document.writeln('		var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");');
document.writeln('		document.write(unescape("%3Cscript src=\'" + _bdhmProtocol + "hm.baidu.com/h.js%3F029f24026f94849a03fdfb06c34e2539\' type=\'text/javascript\'%3E%3C/script%3E"))');
document.writeln('        </script><br>');
document.writeln('		沪卫（中医）网审【2012】第10026号</div>');
document.writeln('	  <div id="copyright_iocOne"><a href="http://e.weibo.com/021huamei?ref=http%3A%2F%2Fwww.shhuamei.cn%2F&sudaref=www.shhuamei.cn" target="_blank"></a></div>');
document.writeln('	  <div id="copyright_ioctwo"><a href="http://e.t.qq.com/q1765847979" target="_blank"></a></div>');
document.writeln('	  <div id="copyright_iocthree"><a href="http://user.qzone.qq.com/1678083243" target="_blank"></a></div>');
document.writeln('	  <div id="copyright_iocfour"><a href="javascript:void(0);"></a> </div>');
document.writeln('	</div>');
document.writeln('  </div>');
document.writeln('  <script src="sendmessage.js"/*tpa=http://baidu.shhuamei.cn/js/sendmessage.js*/></script>');
document.writeln('</footer>');*/